# Airbnb_Open_Data.csv DATASET

In [1]:
import numpy as np
import pandas as pd 


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\LENOVO\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\LENOVO\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\LENOVO\anaconda3\lib\site

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\LENOVO\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\LENOVO\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\LENOVO\anaconda3\lib\site

AttributeError: _ARRAY_API not found

In [2]:
df = pd.read_csv("Airbnb_Open_Data.csv ")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1300\674119030.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv ")


In [3]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN


In [4]:
df.index

RangeIndex(start=0, stop=102599, step=1)

In [5]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN


In [6]:
df.tail()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN


In [7]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   id                              102599 non-null  int64  
 1   NAME                            102349 non-null  object 
 2   host id                         102599 non-null  int64  
 3   host_identity_verified          102310 non-null  object 
 4   host name                       102193 non-null  object 
 5   neighbourhood group             102570 non-null  object 
 6   neighbourhood                   102583 non-null  object 
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object 
 10  country code                    102468 non-null  object 
 11  instant_bookable                102494 non-null  object 
 12  cancellation_pol

In [9]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [10]:
df.shape

(102599, 26)

In [11]:
df.shape[0]

102599

In [12]:
df.shape[1]

26

In [13]:
df.memory_usage()

Index                                128
id                                820792
NAME                              820792
host id                           820792
host_identity_verified            820792
host name                         820792
neighbourhood group               820792
neighbourhood                     820792
lat                               820792
long                              820792
country                           820792
country code                      820792
instant_bookable                  820792
cancellation_policy               820792
room type                         820792
Construction year                 820792
price                             820792
service fee                       820792
minimum nights                    820792
number of reviews                 820792
last review                       820792
reviews per month                 820792
review rate number                820792
calculated host listings count    820792
availability 365

In [14]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [15]:
df["NAME"].value_counts()

NAME
Home away from home                       33
Water View King Bed Hotel Room            30
Hillside Hotel                            30
Brooklyn Apartment                        27
New york Multi-unit building              27
                                          ..
CBG CtyBGd HelpsHaiti rm#1:1-4             1
CBG Helps Haiti Room#2.5                   1
CBG Helps Haiti Rm #2                      1
MAISON DES SIRENES1,bohemian apartment     1
Sunny Bedroom Across Prospect Park         1
Name: count, Length: 61281, dtype: int64

In [16]:
df["NAME"].unique()

array(['Clean & quiet apt home by the park', 'Skylit Midtown Castle',
       'THE VILLAGE OF HARLEM....NEW YORK !', ...,
       'Elmhurst 1st Fl Rightl Bedroom',
       'Elmhurst 1st Floor BR w/ Pvt. Bath&Balcony',
       'Parisian Style Apartment in Heart of Brooklyn'],
      shape=(61282,), dtype=object)

In [17]:
df["NAME"].isnull().sum()

np.int64(250)

In [18]:
df["host id"].value_counts()

host id
78730595133    2
50358760342    2
89461531863    2
86549670696    2
15675388930    2
              ..
56933792344    1
59244531460    1
93276330836    1
76192930914    1
97186426683    1
Name: count, Length: 102057, dtype: int64

In [19]:
df["host id"].unique()

array([80014485718, 52335172823, 78829239556, ..., 23801060917,
       15593031571, 93578954226], shape=(102057,))

In [20]:
df["host id"].isnull().sum()

np.int64(0)

In [21]:
df["host_identity_verified"].value_counts()

host_identity_verified
unconfirmed    51200
verified       51110
Name: count, dtype: int64

In [22]:
df["host_identity_verified"].unique()

array(['unconfirmed', 'verified', nan], dtype=object)

In [23]:
df.dropna(subset=['host_identity_verified'], inplace=True)

In [24]:
df["host_identity_verified"].unique()

array(['unconfirmed', 'verified'], dtype=object)

In [25]:
df["hid_numeric"] = df["host_identity_verified"].apply(lambda x : 0 if x == "unconfirmed" else  1)

In [26]:
df.head(5)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1


In [27]:
df.drop(columns = "host_identity_verified",inplace = True)

In [28]:
df.head(5)

,id,NAME,host id,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1
3,1002755,NaN,85098326012,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1


In [29]:
df.isnull().sum()

id                                     0
NAME                                 238
host id                                0
host name                            405
neighbourhood group                   21
neighbourhood                         16
lat                                    8
long                                   8
country                              529
country code                         123
instant_bookable                      97
cancellation_policy                   73
room type                              0
Construction year                    197
price                                243
service fee                          272
minimum nights                       399
number of reviews                    183
last review                        15851
reviews per month                  15835
review rate number                   312
calculated host listings count       310
availability 365                     440
house_rules                        52012
license         

In [31]:
df["id"].value_counts()

id
20379886    2
20380438    2
20380991    2
20381543    2
20382095    2
           ..
57347534    1
57348087    1
57348639    1
57349191    1
57349744    1
Name: count, Length: 101769, dtype: int64

In [32]:
df["id"].isnull().sum()

np.int64(0)

In [33]:
df.head()

,id,NAME,host id,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1
3,1002755,NaN,85098326012,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1


In [34]:
df["host name"].value_counts()

host name
Michael            881
David              760
John               578
Alex               546
Sonder (NYC)       513
                  ... 
Anna B               1
Natalie And Dan      1
Inhee                1
Shannon & Ryan       1
Kaleel               1
Name: count, Length: 13174, dtype: int64

In [35]:
df["host name"].unique()

array(['Madaline', 'Jenna', 'Garry', ..., 'Anna B', 'Natalie And Dan',
       'Apostle John'], shape=(13175,), dtype=object)

In [36]:
df["host name"].isnull().sum()

np.int64(405)

In [37]:
df.dropna(subset=['host name'], inplace=True)

In [38]:
df["host name"].isnull().sum()

np.int64(0)

In [39]:
df["host name"].value_counts()

host name
Michael            881
David              760
John               578
Alex               546
Sonder (NYC)       513
                  ... 
Anna B               1
Natalie And Dan      1
Inhee                1
Shannon & Ryan       1
Kaleel               1
Name: count, Length: 13174, dtype: int64

In [40]:
df["neighbourhood group"].value_counts()

neighbourhood group
Manhattan        43497
Brooklyn         41555
Queens           13191
Bronx             2695
Staten Island      945
brookln              1
manhatan             1
Name: count, dtype: int64

In [41]:
df["neighbourhood group"].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [42]:
df["neighbourhood group"].isnull().sum()

np.int64(20)

In [43]:
df.dropna(subset=['neighbourhood group'], inplace=True)

In [44]:
df["neighbourhood group"].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens',
       'Staten Island', 'Bronx'], dtype=object)

In [45]:
df["neighbourhood group"].value_counts()

neighbourhood group
Manhattan        43497
Brooklyn         41555
Queens           13191
Bronx             2695
Staten Island      945
brookln              1
manhatan             1
Name: count, dtype: int64

In [46]:
df['neighbourhood group'] = df['neighbourhood group'].astype(str).str.title()

In [47]:
df["neighbourhood group"].value_counts()

neighbourhood group
Manhattan        43497
Brooklyn         41555
Queens           13191
Bronx             2695
Staten Island      945
Brookln              1
Manhatan             1
Name: count, dtype: int64

In [48]:
df["neighbourhood group"].isnull().sum()

np.int64(0)

In [49]:
# First, clean the 'neighbourhood group' column by stripping whitespace
df['neighbourhood group'] = df['neighbourhood group'].astype(str).str.strip()

# Then, apply the lambda function with correctly formatted comparison strings
df["ng__numeric"] = df["neighbourhood group"].apply(lambda x: 
    0 if x == "Manhattan" else
    1 if x == "Brooklyn" else
    2 if x == "Queens" else
    3 if x == "Bronx" else
    4 if x == "Staten Island" else
    5 if x == "Brookln" else
    6
)


In [50]:
df.head()

,id,NAME,host id,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0
3,1002755,NaN,85098326012,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0


In [51]:
df.drop(columns = "neighbourhood group",inplace = True)

In [52]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,instant_bookable,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,False,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,False,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,True,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,False,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,True,...,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0


In [53]:
df["neighbourhood"].value_counts()

neighbourhood
Bedford-Stuyvesant        7884
Williamsburg              7720
Harlem                    5410
Bushwick                  4955
Hell's Kitchen            3940
                          ... 
Rossville                    3
Gerritsen Beach              3
Fort Wadsworth               2
Glen Oaks                    2
Chelsea, Staten Island       1
Name: count, Length: 224, dtype: int64

In [54]:
df["neighbourhood"].unique()

array(['Kensington', 'Midtown', 'Clinton Hill', 'East Harlem',
       'Murray Hill', 'Bedford-Stuyvesant', "Hell's Kitchen",
       'Upper West Side', 'Chinatown', 'South Slope', 'West Village',
       'Williamsburg', 'Fort Greene', 'Chelsea', 'Park Slope', 'Inwood',
       'East Village', 'Harlem', 'Greenpoint', 'Bushwick', 'Flatbush',
       'Long Island City', 'Kips Bay', 'Lower East Side', 'SoHo',
       'Upper East Side', 'Brooklyn Heights', 'Prospect Heights',
       'Carroll Gardens', 'Washington Heights', 'Gowanus',
       'Prospect-Lefferts Gardens', 'Flatlands', 'Cobble Hill',
       'Flushing', 'Boerum Hill', 'Sunnyside', 'DUMBO',
       'Financial District', 'Ridgewood', 'Morningside Heights',
       'Middle Village', 'Ditmars Steinway', 'Flatiron District',
       'Windsor Terrace', 'Roosevelt Island', 'Greenwich Village',
       'Little Italy', 'East Flatbush', 'Tompkinsville', 'Astoria',
       'Clason Point', 'Crown Heights', 'Kingsbridge', 'Two Bridges',
       'Rockaw

In [55]:
df["neighbourhood"].isnull().sum()

np.int64(16)

In [56]:
df.dropna(subset=['neighbourhood'], inplace=True)

In [57]:
df["neighbourhood"].isnull().sum()

np.int64(0)

In [58]:
df["id"].isnull().sum()

np.int64(0)

In [59]:
df["lat"].value_counts()

lat
40.76411    36
40.71813    32
40.76125    27
40.73756    27
40.72440    25
            ..
40.79627     1
40.64840     1
40.79647     1
40.82298     1
40.86019     1
Name: count, Length: 21946, dtype: int64

In [60]:
df["lat"].unique()

array([40.64749, 40.75362, 40.68514, ..., 40.63639, 40.60614, 40.83083],
      shape=(21947,))

In [61]:
df["lat"].isnull().sum()

np.int64(8)

In [62]:
df.dropna(subset=['lat'], inplace=True)

In [63]:
df["lat"].isnull().sum()

np.int64(0)

In [64]:
df = df[(df['lat'] >= -90) & (df['lat'] <= 90)]

In [65]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,instant_bookable,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,False,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,False,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,True,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,False,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,True,...,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0


In [66]:
df["lat"].isnull().sum()

np.int64(0)

In [67]:
df["long"].value_counts()

long
-73.99371    44
-73.95350    39
-73.94791    37
-73.95427    36
-73.94977    34
             ..
-73.85846     1
-73.84716     1
-73.77202     1
-73.77937     1
-73.85167     1
Name: count, Length: 17741, dtype: int64

In [68]:
df["long"].unique()

array([-73.97237, -73.98377, -73.95976, ..., -73.75246, -73.7514 ,
       -73.77419], shape=(17741,))

In [69]:
df["long"].isnull().sum()

np.int64(0)

In [70]:
df["country"].value_counts()

country
United States    101336
Name: count, dtype: int64

In [71]:
df["country"].unique()

array(['United States', nan], dtype=object)

In [72]:
df["country"].isnull().sum()

np.int64(525)

In [73]:
df['country'] = df['country'].astype(str).str.strip()

In [74]:
df.dropna(subset=['country'], inplace=True)

In [75]:
df["country"].isnull().sum()

np.int64(0)

In [76]:
df["country"].unique()

array(['United States', 'nan'], dtype=object)

In [77]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,instant_bookable,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,False,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,False,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,True,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,False,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,True,...,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0


In [78]:
df["country code"].value_counts()

country code
US    101744
Name: count, dtype: int64

In [79]:
df["country code"].unique()

array(['US', nan], dtype=object)

In [80]:
df["country code"].isnull().sum()

np.int64(117)

In [81]:
df.dropna(subset=['country code'], inplace=True)

In [82]:
df["country code"].isnull().sum()

np.int64(0)

In [83]:
df["country code"].unique()

array(['US'], dtype=object)

In [84]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,instant_bookable,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,False,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,False,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,True,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,False,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,True,...,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0


In [85]:
df["instant_bookable"].value_counts()

instant_bookable
False    51097
True     50647
Name: count, dtype: int64

In [86]:
df["instant_bookable"].unique()

array([False, True], dtype=object)

In [87]:
df["instant_bookable"].isnull().sum()

np.int64(0)

In [88]:
# Map boolean values to integers
df["ib__numeric"] = df["instant_bookable"].map({True: 0, False: 1})


In [89]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,instant_bookable,...,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,False,...,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,False,...,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,True,...,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,False,...,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,True,...,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0


In [90]:
df.drop(columns = "instant_bookable",inplace = True)

In [91]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,cancellation_policy,...,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,strict,...,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,moderate,...,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,moderate,...,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,0,1,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,moderate,...,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,flexible,...,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0


In [92]:
df["cancellation_policy"].value_counts()

cancellation_policy
moderate    34085
strict      33851
flexible    33808
Name: count, dtype: int64

In [93]:
df["cancellation_policy"].unique()

array(['strict', 'moderate', 'flexible'], dtype=object)

In [94]:
df["cancellation_policy"].isnull().sum()

np.int64(0)

In [95]:
df["cp__numeric"] = df["cancellation_policy"].apply(lambda x: 
    0 if x.strip() == "moderate" else
    1 if x.strip() == "strict" else
    2                                                
)

In [96]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,cancellation_policy,...,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,strict,...,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,moderate,...,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,moderate,...,4.64,4.0,1.0,322.0,NaN,NaN,0,1,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,moderate,...,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,flexible,...,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2


In [97]:
df.drop(columns = "cancellation_policy",inplace = True) 

In [98]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,room type,...,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,Private room,...,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,Entire home/apt,...,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,Entire home/apt,...,4.64,4.0,1.0,322.0,NaN,NaN,0,1,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,Entire home/apt,...,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,Entire home/apt,...,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2


In [99]:
df["room type"].value_counts()

room type
Entire home/apt    53287
Private room       46128
Shared room         2213
Hotel room           116
Name: count, dtype: int64

In [100]:
df["room type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [101]:
df["room type"].isnull().sum()

np.int64(0)

In [102]:
df['room type'] = df['room type'].str.title().replace({
    'Entire Home': 'Entire Home/Apt',
    'Private Room': 'Private Room',
    'Shared Room': 'Shared Room',
    'Hotel Room': 'Hotel Room'
})

In [103]:
df["room type"].value_counts()

room type
Entire Home/Apt    53287
Private Room       46128
Shared Room         2213
Hotel Room           116
Name: count, dtype: int64

In [104]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,room type,...,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,Private Room,...,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,Entire Home/Apt,...,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,Entire Home/Apt,...,4.64,4.0,1.0,322.0,NaN,NaN,0,1,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,Entire Home/Apt,...,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,Entire Home/Apt,...,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2


In [105]:
df["rt__numeric"] = df["room type"].apply(lambda x: 
    0 if x.strip() == "Entire Home/Apt" else
    1 if x.strip() == "Private Room" else
    2 if x.strip() == "Shared Room" else
    3
    
)

In [106]:
df.head(10)

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,room type,...,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,Private Room,...,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,Entire Home/Apt,...,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,Entire Home/Apt,...,4.0,1.0,322.0,NaN,NaN,0,1,0,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,Entire Home/Apt,...,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,Entire Home/Apt,...,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2,0
7,1005202,BlissArtsSpace!,90821839709,Emma,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,Private Room,...,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN,0,1,1,0,1
8,1005754,Large Furnished Room Near B'way,79384379533,Evelyn,Hell's Kitchen,40.76489,-73.98493,United States,US,Private Room,...,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1,0,0,1,1
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,Carl,Upper West Side,40.80178,-73.96723,United States,US,Private Room,...,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN,0,0,1,1,1
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,Miranda,Chinatown,40.71344,-73.99037,United States,US,Entire Home/Apt,...,3.0,4.0,1.0,NaN,NaN,1,0,1,2,0
11,1007411,Beautiful 1br on Upper West Side,18824631834,Alan,Upper West Side,40.80316,-73.96545,United States,US,Entire Home/Apt,...,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",NaN,1,0,0,2,0


In [107]:
df.drop(columns = "room type",inplace = True)

In [108]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,2020.0,...,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,2007.0,...,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,2005.0,...,4.0,1.0,322.0,NaN,NaN,0,1,0,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,2009.0,...,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,2013.0,...,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2,0


In [109]:
df["Construction year"].value_counts()

Construction year
2014.0    5196
2006.0    5182
2008.0    5178
2019.0    5157
2009.0    5124
2010.0    5116
2020.0    5111
2005.0    5093
2012.0    5092
2022.0    5092
2003.0    5080
2007.0    5061
2015.0    5060
2017.0    5030
2011.0    5026
2021.0    5007
2004.0    4996
2018.0    4993
2013.0    4986
2016.0    4979
Name: count, dtype: int64

In [110]:
df["Construction year"].unique()

array([2020., 2007., 2005., 2009., 2013., 2015., 2004., 2008., 2010.,
       2019., 2018., 2016., 2003., 2011., 2017., 2006., 2022., 2014.,
       2012., 2021.,   nan])

In [111]:
df["Construction year"].isnull().sum()

np.int64(185)

In [112]:
df.dropna(subset=['Construction year'], inplace=True)

In [113]:
df["Construction year"].unique()

array([2020., 2007., 2005., 2009., 2013., 2015., 2004., 2008., 2010.,
       2019., 2018., 2016., 2003., 2011., 2017., 2006., 2022., 2014.,
       2012., 2021.])

In [114]:
df["Construction year"].isnull().sum()

np.int64(0)

In [115]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365', 'house_rules',
       'license', 'hid_numeric', 'ng__numeric', 'ib__numeric', 'cp__numeric',
       'rt__numeric'],
      dtype='object')

In [116]:
df["price"].value_counts()

price
$206       133
$481       129
$1,056     129
$573       127
$833       126
          ... 
$369        58
$923        57
$786        53
$187        52
$89         52
Name: count, Length: 1151, dtype: int64

In [117]:
df["price"].unique()

array(['$966 ', '$142 ', '$368 ', ..., '$905 ', '$309 ', '$770 '],
      shape=(1152,), dtype=object)

In [118]:
df["price"].isnull().sum()

np.int64(228)

In [119]:
df['price'] = df['price'].replace('[\$,]', '', regex=True)


In [120]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [121]:
df["price"].value_counts()

price
206.0     133
481.0     129
1056.0    129
573.0     127
833.0     126
         ... 
369.0      58
923.0      57
786.0      53
187.0      52
89.0       52
Name: count, Length: 1151, dtype: int64

In [122]:
df["price"].unique()

array([966., 142., 368., ..., 905., 309., 770.], shape=(1152,))

In [123]:
df["price"].isnull().sum()

np.int64(228)

In [124]:
df.dropna(subset=['price'], inplace=True)

In [125]:
df["price"].isnull().sum()

np.int64(0)

In [126]:
df["price"].unique()

array([966., 142., 368., ..., 905., 309., 770.], shape=(1151,))

In [127]:
df["price"].shape[0]

101331

In [128]:
df["service fee"].shape[0]

101331

In [129]:
df["service fee"].value_counts()

service fee
$216     518
$41      515
$81      514
$177     509
$57      509
        ... 
$58      380
$73      377
$67      377
$10      263
$240     247
Name: count, Length: 231, dtype: int64

In [130]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,review rate number,calculated host listings count,availability 365,house_rules,license,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
0,1001254,Clean & quiet apt home by the park,80014485718,Madaline,Kensington,40.64749,-73.97237,United States,US,2020.0,...,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,0,1,1,1,1
1,1002102,Skylit Midtown Castle,52335172823,Jenna,Midtown,40.75362,-73.98377,United States,US,2007.0,...,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,1,0,1,0,0
3,1002755,NaN,85098326012,Garry,Clinton Hill,40.68514,-73.95976,United States,US,2005.0,...,4.0,1.0,322.0,NaN,NaN,0,1,0,0,0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Lyndon,East Harlem,40.79851,-73.94399,United States,US,2009.0,...,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,1,0,1,0,0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Michelle,Murray Hill,40.74767,-73.97500,United States,US,2013.0,...,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,1,0,0,2,0


In [131]:
df["service fee"].unique()

array(['$193 ', '$28 ', '$74 ', '$41 ', '$115 ', '$212 ', '$204 ', '$58 ',
       '$64 ', '$121 ', '$116 ', '$30 ', nan, '$38 ', '$222 ', '$219 ',
       '$113 ', '$171 ', '$12 ', '$183 ', '$92 ', '$73 ', '$42 ', '$146 ',
       '$180 ', '$67 ', '$51 ', '$181 ', '$88 ', '$205 ', '$109 ',
       '$156 ', '$131 ', '$165 ', '$129 ', '$207 ', '$17 ', '$63 ',
       '$147 ', '$48 ', '$213 ', '$211 ', '$182 ', '$117 ', '$39 ',
       '$25 ', '$10 ', '$118 ', '$76 ', '$69 ', '$168 ', '$106 ', '$13 ',
       '$152 ', '$105 ', '$221 ', '$132 ', '$114 ', '$189 ', '$90 ',
       '$186 ', '$66 ', '$225 ', '$19 ', '$238 ', '$119 ', '$98 ', '$34 ',
       '$227 ', '$32 ', '$101 ', '$23 ', '$162 ', '$77 ', '$190 ', '$75 ',
       '$231 ', '$133 ', '$35 ', '$82 ', '$120 ', '$21 ', '$145 ', '$65 ',
       '$100 ', '$144 ', '$26 ', '$89 ', '$218 ', '$104 ', '$44 ', '$79 ',
       '$163 ', '$22 ', '$37 ', '$11 ', '$102 ', '$240 ', '$46 ', '$175 ',
       '$210 ', '$215 ', '$191 ', '$16 ', '$94 ', '$233 '

In [132]:
df["service fee"].isnull().sum()

np.int64(229)

In [133]:
df['service fee'] = df['service fee'].replace('[\$,]', '', regex=True)

In [134]:
df['service fee'] = pd.to_numeric(df['service fee'], errors='coerce')

In [135]:
df["service fee"].value_counts()

service fee
216.0    518
41.0     515
81.0     514
177.0    509
57.0     509
        ... 
58.0     380
73.0     377
67.0     377
10.0     263
240.0    247
Name: count, Length: 231, dtype: int64

In [136]:
df["service fee"].unique()

array([193.,  28.,  74.,  41., 115., 212., 204.,  58.,  64., 121., 116.,
        30.,  nan,  38., 222., 219., 113., 171.,  12., 183.,  92.,  73.,
        42., 146., 180.,  67.,  51., 181.,  88., 205., 109., 156., 131.,
       165., 129., 207.,  17.,  63., 147.,  48., 213., 211., 182., 117.,
        39.,  25.,  10., 118.,  76.,  69., 168., 106.,  13., 152., 105.,
       221., 132., 114., 189.,  90., 186.,  66., 225.,  19., 238., 119.,
        98.,  34., 227.,  32., 101.,  23., 162.,  77., 190.,  75., 231.,
       133.,  35.,  82., 120.,  21., 145.,  65., 100., 144.,  26.,  89.,
       218., 104.,  44.,  79., 163.,  22.,  37.,  11., 102., 240.,  46.,
       175., 210., 215., 191.,  16.,  94., 233., 206., 157.,  15., 229.,
       179.,  85., 136., 170., 201., 123.,  36.,  14., 187., 198.,  54.,
       122., 184., 208., 140., 148.,  68., 196., 137.,  70., 228., 209.,
       230., 134.,  20., 110., 234., 151., 172., 107., 138., 194., 139.,
        24., 158.,  31., 124., 203., 232., 192.,  8

In [137]:
df["service fee"].isnull().sum()

np.int64(229)

In [138]:
df.dropna(subset=['service fee'], inplace=True)

In [139]:
df["service fee"].isnull().sum()

np.int64(0)

In [140]:
df["minimum nights"].value_counts()

minimum nights
 1.0      25074
 2.0      23286
 3.0      15890
 30.0     11477
 4.0       6523
          ...  
-125.0        1
 125.0        1
 34.0         1
 458.0        1
 825.0        1
Name: count, Length: 148, dtype: int64

In [141]:
df["minimum nights"].unique()

array([ 1.000e+01,  3.000e+01,  3.000e+00,  4.500e+01,  2.000e+00,
        1.000e+00,  5.000e+00,  4.000e+00,  6.000e+01,  7.000e+00,
              nan,  1.800e+02,  9.000e+00,  3.100e+01,  6.000e+00,
        1.500e+01,  8.000e+00,  4.700e+01,  8.100e+01,  1.440e+02,
        3.710e+02,  2.680e+02, -1.000e+01,  1.890e+02,  3.400e+02,
        1.280e+02,  3.500e+02,  1.660e+02,  1.100e+02,  5.700e+01,
        1.420e+02,  3.660e+02,  1.400e+01,  2.800e+01,  2.000e+02,
        5.000e+01,  3.990e+02,  1.100e+01,  4.520e+02,  1.300e+01,
        3.455e+03,  2.100e+01,  2.700e+01,  1.800e+01, -1.000e+00,
        2.000e+01, -1.200e+01,  4.000e+01,  3.980e+02, -2.000e+00,
        6.500e+01, -3.000e+00,  9.000e+01,  2.900e+01,  5.500e+01,
        1.200e+02,  3.650e+02,  1.220e+02,  1.900e+01,  2.400e+02,
        8.800e+01,  1.150e+02,  1.500e+02,  3.700e+02,  1.600e+01,
        1.810e+02,  2.600e+01,  8.000e+01,  2.500e+01,  2.650e+02,
        3.000e+02,  1.700e+01,  5.900e+01,  1.850e+02,  3.600e

In [142]:
df["minimum nights"].isnull().sum()

np.int64(386)

In [143]:
df['minimum nights'] = pd.to_numeric(df['minimum nights'], errors='coerce')

In [144]:
df["minimum nights"].unique()

array([ 1.000e+01,  3.000e+01,  3.000e+00,  4.500e+01,  2.000e+00,
        1.000e+00,  5.000e+00,  4.000e+00,  6.000e+01,  7.000e+00,
              nan,  1.800e+02,  9.000e+00,  3.100e+01,  6.000e+00,
        1.500e+01,  8.000e+00,  4.700e+01,  8.100e+01,  1.440e+02,
        3.710e+02,  2.680e+02, -1.000e+01,  1.890e+02,  3.400e+02,
        1.280e+02,  3.500e+02,  1.660e+02,  1.100e+02,  5.700e+01,
        1.420e+02,  3.660e+02,  1.400e+01,  2.800e+01,  2.000e+02,
        5.000e+01,  3.990e+02,  1.100e+01,  4.520e+02,  1.300e+01,
        3.455e+03,  2.100e+01,  2.700e+01,  1.800e+01, -1.000e+00,
        2.000e+01, -1.200e+01,  4.000e+01,  3.980e+02, -2.000e+00,
        6.500e+01, -3.000e+00,  9.000e+01,  2.900e+01,  5.500e+01,
        1.200e+02,  3.650e+02,  1.220e+02,  1.900e+01,  2.400e+02,
        8.800e+01,  1.150e+02,  1.500e+02,  3.700e+02,  1.600e+01,
        1.810e+02,  2.600e+01,  8.000e+01,  2.500e+01,  2.650e+02,
        3.000e+02,  1.700e+01,  5.900e+01,  1.850e+02,  3.600e

In [145]:
df = df[df['minimum nights'] > 0]

In [146]:
df["minimum nights"].unique()

array([1.000e+01, 3.000e+01, 3.000e+00, 4.500e+01, 2.000e+00, 1.000e+00,
       5.000e+00, 4.000e+00, 6.000e+01, 7.000e+00, 1.800e+02, 9.000e+00,
       3.100e+01, 6.000e+00, 1.500e+01, 8.000e+00, 4.700e+01, 8.100e+01,
       1.440e+02, 3.710e+02, 2.680e+02, 1.890e+02, 3.400e+02, 1.280e+02,
       3.500e+02, 1.660e+02, 1.100e+02, 5.700e+01, 1.420e+02, 3.660e+02,
       1.400e+01, 2.800e+01, 2.000e+02, 5.000e+01, 3.990e+02, 1.100e+01,
       4.520e+02, 1.300e+01, 3.455e+03, 2.100e+01, 2.700e+01, 1.800e+01,
       2.000e+01, 4.000e+01, 3.980e+02, 6.500e+01, 9.000e+01, 2.900e+01,
       5.500e+01, 1.200e+02, 3.650e+02, 1.220e+02, 1.900e+01, 2.400e+02,
       8.800e+01, 1.150e+02, 1.500e+02, 3.700e+02, 1.600e+01, 1.810e+02,
       2.600e+01, 8.000e+01, 2.500e+01, 2.650e+02, 3.000e+02, 1.700e+01,
       5.900e+01, 1.850e+02, 3.600e+02, 5.600e+01, 1.200e+01, 7.000e+01,
       3.900e+01, 2.400e+01, 3.200e+01, 1.000e+03, 2.700e+02, 2.200e+01,
       7.500e+01, 2.500e+02, 6.200e+01, 2.300e+01, 

In [147]:
df["minimum nights"].value_counts()

minimum nights
1.0      25074
2.0      23286
3.0      15890
30.0     11477
4.0       6523
         ...  
119.0        1
125.0        1
34.0         1
458.0        1
825.0        1
Name: count, Length: 139, dtype: int64

In [148]:
df.dropna(subset=['minimum nights'], inplace=True)

In [149]:
df["minimum nights"].isnull().sum()

np.int64(0)

In [150]:
df["number of reviews"].value_counts()

number of reviews
0.0      15480
1.0      10213
2.0       7058
3.0       5283
4.0       4076
         ...  
400.0        1
328.0        1
480.0        1
351.0        1
300.0        1
Name: count, Length: 474, dtype: int64

In [151]:
df["number of reviews"].unique()

array([9.000e+00, 4.500e+01, 2.700e+02, 7.400e+01, 4.900e+01, 4.300e+02,
       1.180e+02, 1.600e+02, 5.300e+01, 1.670e+02, 1.130e+02, 1.680e+02,
       0.000e+00, 2.310e+02, 2.450e+02, 1.500e+01, 8.100e+01, 9.700e+01,
       1.050e+02, 1.900e+01, 1.380e+02, 2.100e+01, 5.000e+00, 6.600e+01,
       2.700e+01, 1.910e+02, 4.000e+00, 3.380e+02, 1.480e+02, 1.060e+02,
       2.300e+01, 6.100e+01, 5.400e+01, 7.000e+01, 1.600e+01, 9.400e+01,
       2.500e+01, 1.940e+02, 2.900e+01, 1.700e+02, 3.340e+02, 1.200e+01,
       3.600e+01, 6.300e+01, 1.550e+02, 2.600e+02, 7.300e+01, 1.930e+02,
       2.000e+00, 2.000e+02, 7.900e+01, 3.400e+01, 1.400e+01, 8.000e+01,
       1.140e+02, 8.600e+01, 3.800e+01, 1.800e+01, 2.060e+02, 1.000e+01,
       1.220e+02, 3.300e+01, 5.200e+01, 1.260e+02, 8.200e+01, 3.700e+01,
       2.040e+02, 6.900e+01, 1.920e+02, 1.700e+01, 2.220e+02, 2.050e+02,
       7.000e+00, 1.080e+02, 4.580e+02, 4.100e+01, 1.000e+00, 1.830e+02,
       1.890e+02, 3.500e+01, 1.710e+02, 9.200e+01, 

In [152]:
df["number of reviews"].isnull().sum()

np.int64(180)

In [153]:
df.isnull().sum()

id                                     0
NAME                                 220
host id                                0
host name                              0
neighbourhood                          0
lat                                    0
long                                   0
country                                0
country code                           0
Construction year                      0
price                                  0
service fee                            0
minimum nights                         0
number of reviews                    180
last review                        15617
reviews per month                  15615
review rate number                   275
calculated host listings count       310
availability 365                     382
house_rules                        51287
license                           100702
hid_numeric                            0
ng__numeric                            0
ib__numeric                            0
cp__numeric     

In [154]:
df['number of reviews'] = pd.to_numeric(df['number of reviews'], errors='coerce')

In [155]:
df["number of reviews"].unique()

array([9.000e+00, 4.500e+01, 2.700e+02, 7.400e+01, 4.900e+01, 4.300e+02,
       1.180e+02, 1.600e+02, 5.300e+01, 1.670e+02, 1.130e+02, 1.680e+02,
       0.000e+00, 2.310e+02, 2.450e+02, 1.500e+01, 8.100e+01, 9.700e+01,
       1.050e+02, 1.900e+01, 1.380e+02, 2.100e+01, 5.000e+00, 6.600e+01,
       2.700e+01, 1.910e+02, 4.000e+00, 3.380e+02, 1.480e+02, 1.060e+02,
       2.300e+01, 6.100e+01, 5.400e+01, 7.000e+01, 1.600e+01, 9.400e+01,
       2.500e+01, 1.940e+02, 2.900e+01, 1.700e+02, 3.340e+02, 1.200e+01,
       3.600e+01, 6.300e+01, 1.550e+02, 2.600e+02, 7.300e+01, 1.930e+02,
       2.000e+00, 2.000e+02, 7.900e+01, 3.400e+01, 1.400e+01, 8.000e+01,
       1.140e+02, 8.600e+01, 3.800e+01, 1.800e+01, 2.060e+02, 1.000e+01,
       1.220e+02, 3.300e+01, 5.200e+01, 1.260e+02, 8.200e+01, 3.700e+01,
       2.040e+02, 6.900e+01, 1.920e+02, 1.700e+01, 2.220e+02, 2.050e+02,
       7.000e+00, 1.080e+02, 4.580e+02, 4.100e+01, 1.000e+00, 1.830e+02,
       1.890e+02, 3.500e+01, 1.710e+02, 9.200e+01, 

In [156]:
df = df[df['number of reviews'] >= 0]

In [157]:
df["number of reviews"].value_counts()

number of reviews
0.0      15480
1.0      10213
2.0       7058
3.0       5283
4.0       4076
         ...  
400.0        1
328.0        1
480.0        1
351.0        1
300.0        1
Name: count, Length: 474, dtype: int64

In [158]:
df.dropna(subset=['number of reviews'], inplace=True)

In [159]:
df["number of reviews"].isnull().sum()

np.int64(0)

In [160]:
df["calculated host listings count"].value_counts()

calculated host listings count
1.0     62146
2.0     14179
3.0      6425
4.0      3495
5.0      1952
        ...  
22.0       20
86.0       20
55.0       15
46.0        9
80.0        7
Name: count, Length: 77, dtype: int64

In [161]:
df["calculated host listings count"].unique()

array([  6.,   2.,   1.,   4.,   3.,  nan,   5.,   7.,  28.,  11.,   8.,
         9.,  52.,  18.,  15.,  19.,  10.,  39.,  13.,  26.,  29.,  12.,
        21.,  96.,  14.,  34.,  43., 121.,  37.,  49.,  31.,  91.,  16.,
        87.,  33.,  23.,  50.,  20.,  25., 232.,  17.,  47., 103.,  65.,
        30.,  27., 327.,  32.,  53., 208., 171.,  44.,  48., 108.,  51.,
       161., 152.,  83.,  24.,  22., 126.,  54.,  66.,  59.,  62., 102.,
       186., 125.,  55.,  63.,  67.,  58.,  56.,  80.,  46., 218.,  86.,
       332.])

In [162]:
df["calculated host listings count"].isnull().sum()

np.int64(310)

In [163]:
df.dropna(subset=['calculated host listings count'], inplace=True)

In [164]:
df["calculated host listings count"].unique()

array([  6.,   2.,   1.,   4.,   3.,   5.,   7.,  28.,  11.,   8.,   9.,
        52.,  18.,  15.,  19.,  10.,  39.,  13.,  26.,  29.,  12.,  21.,
        96.,  14.,  34.,  43., 121.,  37.,  49.,  31.,  91.,  16.,  87.,
        33.,  23.,  50.,  20.,  25., 232.,  17.,  47., 103.,  65.,  30.,
        27., 327.,  32.,  53., 208., 171.,  44.,  48., 108.,  51., 161.,
       152.,  83.,  24.,  22., 126.,  54.,  66.,  59.,  62., 102., 186.,
       125.,  55.,  63.,  67.,  58.,  56.,  80.,  46., 218.,  86., 332.])

In [165]:
df["calculated host listings count"].isnull().sum()

np.int64(0)

In [166]:
df.isnull().sum()

id                                     0
NAME                                 220
host id                                0
host name                              0
neighbourhood                          0
lat                                    0
long                                   0
country                                0
country code                           0
Construction year                      0
price                                  0
service fee                            0
minimum nights                         0
number of reviews                      0
last review                        15436
reviews per month                  15434
review rate number                   214
calculated host listings count         0
availability 365                     328
house_rules                        51045
license                           100212
hid_numeric                            0
ng__numeric                            0
ib__numeric                            0
cp__numeric     

In [170]:
df["availability 365"].value_counts()

availability 365
 0.0       23033
 365.0      2450
 364.0      1142
 89.0        741
 1.0         725
           ...  
-6.0          31
 408.0        30
 391.0        30
 401.0        29
 3677.0        1
Name: count, Length: 438, dtype: int64

In [171]:
df["availability 365"].unique()

array([ 2.860e+02,  2.280e+02,  3.220e+02,  2.890e+02,  3.740e+02,
        2.190e+02,  1.800e+02,  3.750e+02,  1.000e+00,  1.630e+02,
        4.700e+01,  6.800e+01,  7.600e+01,  4.160e+02,  2.940e+02,
        2.140e+02,  3.560e+02,  3.540e+02,  3.300e+01,  8.600e+01,
        1.520e+02,  8.300e+01,  2.580e+02,  4.000e+02,  3.400e+01,
        2.030e+02,  3.500e+01,  4.100e+02,  3.880e+02,  1.300e+01,
        6.200e+01,  3.340e+02,  1.660e+02,  1.800e+01,  1.300e+02,
        4.300e+01,  0.000e+00,  3.730e+02,  1.900e+02,  3.350e+02,
        5.200e+01,  7.000e+01,  3.200e+02,  2.930e+02,  5.800e+01,
        2.400e+02,  9.600e+01,  3.000e+02,  4.250e+02,  4.210e+02,
        3.320e+02,  3.610e+02,  3.410e+02,  3.530e+02,  2.130e+02,
        1.370e+02,  3.360e+02,  2.300e+01,  1.900e+01,  3.950e+02,
        7.800e+01,  1.880e+02,  3.380e+02,  6.600e+01,  8.000e+01,
        1.460e+02,  3.820e+02,  3.290e+02,  9.000e+00,  2.560e+02,
       -6.000e+00,  3.190e+02,  5.000e+01,  1.180e+02,  3.500e

In [169]:
df.dropna(subset=['availability 365'], inplace=True)

In [172]:
df["availability 365"].isnull().sum()

np.int64(0)

In [173]:
df["house_rules"].value_counts()

house_rules
#NAME?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [174]:
df["house_rules"].unique()

array(["Clean up and treat the home the way you'd like your home to be treated.  No smoking.",
       'Pet friendly but please confirm with me if the pet you are planning on bringing with you is OK. I have a cute and quiet mixed chihuahua. I could accept more guests (for an extra fee) but this also needs to be confirmed beforehand. Also friends traveling together could sleep in separate beds for an extra fee (the second bed is either a sofa bed or inflatable bed). Smoking is only allowed on the porch.',
       nan, ...,
       '15 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.',
       'House rules: Guests agree to the following terms and conditions 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2

In [175]:
df.drop(columns = "house_rules",inplace = True)

In [177]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365', 'license',
       'hid_numeric', 'ng__numeric', 'ib__numeric', 'cp__numeric',
       'rt__numeric'],
      dtype='object')

In [178]:
df.isnull().sum()

id                                    0
NAME                                210
host id                               0
host name                             0
neighbourhood                         0
lat                                   0
long                                  0
country                               0
country code                          0
Construction year                     0
price                                 0
service fee                           0
minimum nights                        0
number of reviews                     0
last review                       15232
reviews per month                 15232
review rate number                  212
calculated host listings count        0
availability 365                      0
license                           99884
hid_numeric                           0
ng__numeric                           0
ib__numeric                           0
cp__numeric                           0
rt__numeric                           0


In [179]:
df["license"].value_counts()

license
41662/AL    2
Name: count, dtype: int64

In [180]:
df["license"].unique()

array([nan, '41662/AL'], dtype=object)

In [181]:
df.dropna(subset=['license'], inplace=True)

In [182]:
df["license"].unique()

array(['41662/AL'], dtype=object)

In [183]:
df["license"].isnull().sum()

np.int64(0)

In [184]:
df.drop(columns = "license",inplace = True)

In [185]:
df.isnull().sum()

id                                0
NAME                              0
host id                           0
host name                         0
neighbourhood                     0
lat                               0
long                              0
country                           0
country code                      0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
last review                       0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
hid_numeric                       0
ng__numeric                       0
ib__numeric                       0
cp__numeric                       0
rt__numeric                       0
dtype: int64

In [225]:
df.drop(columns = "availability 365",inplace = True) 

In [186]:
df.isnull().sum()

id                                0
NAME                              0
host id                           0
host name                         0
neighbourhood                     0
lat                               0
long                              0
country                           0
country code                      0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
last review                       0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
hid_numeric                       0
ng__numeric                       0
ib__numeric                       0
cp__numeric                       0
rt__numeric                       0
dtype: int64

In [187]:
df.drop(columns = "calculated host listings count",inplace = True)

In [188]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number', 'availability 365',
       'hid_numeric', 'ng__numeric', 'ib__numeric', 'cp__numeric',
       'rt__numeric'],
      dtype='object')

In [189]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,number of reviews,last review,reviews per month,review rate number,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1/3/2016,0.02,1.0,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1/3/2016,0.02,1.0,0.0,0,1,0,2,1


In [190]:
df.isnull().sum()

id                    0
NAME                  0
host id               0
host name             0
neighbourhood         0
lat                   0
long                  0
country               0
country code          0
Construction year     0
price                 0
service fee           0
minimum nights        0
number of reviews     0
last review           0
reviews per month     0
review rate number    0
availability 365      0
hid_numeric           0
ng__numeric           0
ib__numeric           0
cp__numeric           0
rt__numeric           0
dtype: int64

In [191]:
df["review rate number"].value_counts()

review rate number
1.0    2
Name: count, dtype: int64

In [192]:
df["review rate number"].unique()

array([1.])

In [193]:
df["review rate number"].isnull().sum()

np.int64(0)

In [194]:
df.drop(columns ="review rate number",inplace = True )

In [195]:
df.isnull().sum()

id                   0
NAME                 0
host id              0
host name            0
neighbourhood        0
lat                  0
long                 0
country              0
country code         0
Construction year    0
price                0
service fee          0
minimum nights       0
number of reviews    0
last review          0
reviews per month    0
availability 365     0
hid_numeric          0
ng__numeric          0
ib__numeric          0
cp__numeric          0
rt__numeric          0
dtype: int64

In [196]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'availability 365', 'hid_numeric', 'ng__numeric',
       'ib__numeric', 'cp__numeric', 'rt__numeric'],
      dtype='object')

In [197]:
df.isnull().sum()

id                   0
NAME                 0
host id              0
host name            0
neighbourhood        0
lat                  0
long                 0
country              0
country code         0
Construction year    0
price                0
service fee          0
minimum nights       0
number of reviews    0
last review          0
reviews per month    0
availability 365     0
hid_numeric          0
ng__numeric          0
ib__numeric          0
cp__numeric          0
rt__numeric          0
dtype: int64

In [230]:
df["last review"].isnull().sum()

np.int64(0)

In [231]:
df.dropna(subset=["last review"],inplace = True)

In [232]:
df["last review"].isnull().sum()

np.int64(0)

In [233]:
df["last review"].value_counts()

last review
1/3/2016    2
Name: count, dtype: int64

In [234]:
df["last review"].unique()

array(['1/3/2016'], dtype=object)

In [236]:
df['last review'] = pd.to_datetime(df['last review'], errors='coerce')

In [237]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,0.0,0,1,0,2,1


In [238]:
df["last review"].value_counts()

last review
2016-01-03    2
Name: count, dtype: int64

In [239]:
df["last review"].unique()

<DatetimeArray>
['2016-01-03 00:00:00']
Length: 1, dtype: datetime64[ns]

In [204]:
df["reviews per month"].value_counts()

reviews per month
0.02    2
Name: count, dtype: int64

In [205]:
df["reviews per month"].unique()

array([0.02])

In [206]:
df["reviews per month"].isnull().sum()

np.int64(0)

In [207]:
df.dropna(subset=["reviews per month"],inplace = True)

In [208]:
df["reviews per month"].isnull().sum()

np.int64(0)

In [209]:
df["reviews per month"].unique()

array([0.02])

In [213]:
df["reviews per month"] = pd.to_numeric(df["reviews per month"],errors = 'coerce')

In [214]:
df["reviews per month"].unique()

array([0.02])

In [212]:
df["reviews per month"].value_counts()

reviews per month
0.02    2
Name: count, dtype: int64

In [216]:
df = df[df['reviews per month'] >= 0]

In [217]:
df["reviews per month"].unique()

array([0.02])

In [219]:
df.head(5)

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,0.0,0,1,0,2,1


In [220]:
df.head(10)

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,0.0,0,1,0,2,1


In [221]:
df['reviews per month'] = df['reviews per month'].astype(str).str.strip()

In [222]:
df['reviews per month'] = pd.to_numeric(df['reviews per month'], errors='coerce')

In [223]:
df = df.dropna(subset=['reviews per month'])

In [224]:
df = df[df['reviews per month'] >= 0]

In [225]:
df['reviews per month'].unique()

array([0.02])

In [226]:
print(df['reviews per month'].unique())


[0.02]


In [227]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,0.0,0,1,0,2,1


In [228]:
print(df['reviews per month'].head(10).tolist())


[0.02, 0.02]


In [229]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,1/3/2016,0.02,0.0,0,1,0,2,1


In [240]:
df.head()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,0.0,0,1,0,2,1


In [241]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'availability 365', 'hid_numeric', 'ng__numeric',
       'ib__numeric', 'cp__numeric', 'rt__numeric'],
      dtype='object')

In [242]:
df["NAME"].value_counts()

NAME
Cozy 1 BR on Bedford Avenue, Wburg    2
Name: count, dtype: int64

In [243]:
df["NAME"].unique()

array(['Cozy 1 BR on Bedford Avenue, Wburg'], dtype=object)

In [244]:
df["NAME"].isnull().sum()

np.int64(0)

In [245]:
df.head()


,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,0.0,0,1,0,2,1


In [246]:
df.tail()

,id,NAME,host id,host name,neighbourhood,lat,long,country,country code,Construction year,...,minimum nights,number of reviews,last review,reviews per month,availability 365,hid_numeric,ng__numeric,ib__numeric,cp__numeric,rt__numeric
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,191.0,1,1,0,1,1
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,Christina,Williamsburg,40.71764,-73.95689,United States,US,2010.0,...,1.0,1.0,2016-01-03,0.02,0.0,0,1,0,2,1


In [247]:
df.columns

Index(['id', 'NAME', 'host id', 'host name', 'neighbourhood', 'lat', 'long',
       'country', 'country code', 'Construction year', 'price', 'service fee',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'availability 365', 'hid_numeric', 'ng__numeric',
       'ib__numeric', 'cp__numeric', 'rt__numeric'],
      dtype='object')

In [248]:
df.isnull().sum()

id                   0
NAME                 0
host id              0
host name            0
neighbourhood        0
lat                  0
long                 0
country              0
country code         0
Construction year    0
price                0
service fee          0
minimum nights       0
number of reviews    0
last review          0
reviews per month    0
availability 365     0
hid_numeric          0
ng__numeric          0
ib__numeric          0
cp__numeric          0
rt__numeric          0
dtype: int64