In [1]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [50 lines of output]
  Traceback (most recent call last):
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-kr9yhynf\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 36, in __init__
      parsed = _parse_requirement(requirement_string)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-kr9yhynf\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 62, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-kr9yhynf\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 80, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-kr9yhynf\overlay\Lib\site-packages\setuptools\_vendor\packaging\_par

In [2]:
import tensorflow as tf
print(tf.__version__)

C:\Users\LENOVO\anaconda3\lib\site-packages\google\api_core\_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.9) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
C:\Users\LENOVO\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


2.12.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=10000

# One Hot Representation

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6348, 3985, 2764, 4983], [6348, 3985, 2764, 3635], [6348, 2427, 2764, 8410], [5913, 8759, 8337, 2863, 3338], [5913, 8759, 8337, 2863, 1957], [5658, 6348, 8636, 2764, 1440], [3858, 5241, 5546, 2863]]


# Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6348 3985 2764 4983]
 [   0    0    0    0 6348 3985 2764 3635]
 [   0    0    0    0 6348 2427 2764 8410]
 [   0    0    0 5913 8759 8337 2863 3338]
 [   0    0    0 5913 8759 8337 2863 1957]
 [   0    0    0 5658 6348 8636 2764 1440]
 [   0    0    0    0 3858 5241 5546 2863]]


In [13]:
## 10 feature dimesnions
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 6348, 3985, 2764, 4983])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 378ms/step


array([[-0.00713933,  0.02670025,  0.00955595, -0.01016245, -0.02612432,
        -0.02571746, -0.04351426,  0.04922808,  0.03779388,  0.01237991],
       [-0.00713933,  0.02670025,  0.00955595, -0.01016245, -0.02612432,
        -0.02571746, -0.04351426,  0.04922808,  0.03779388,  0.01237991],
       [-0.00713933,  0.02670025,  0.00955595, -0.01016245, -0.02612432,
        -0.02571746, -0.04351426,  0.04922808,  0.03779388,  0.01237991],
       [-0.00713933,  0.02670025,  0.00955595, -0.01016245, -0.02612432,
        -0.02571746, -0.04351426,  0.04922808,  0.03779388,  0.01237991],
       [ 0.01703241,  0.00141624,  0.01836063, -0.04050465, -0.00021738,
         0.0470962 , -0.04713834, -0.0145869 , -0.0093541 ,  0.00981445],
       [-0.04526804, -0.00512029,  0.00670778,  0.00324589, -0.03528035,
         0.02890212, -0.03655505, -0.04958206, -0.02427058, -0.02469977],
       [-0.00189484, -0.03842533, -0.04435733, -0.04152895,  0.03780557,
         0.00536566,  0.03029987, -0.04246242

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 106ms/step
[[[-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432
   -0.02571746 -0.04351426  0.04922808  0.03779388  0.01237991]
  [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432
   -0.02571746 -0.04351426  0.04922808  0.03779388  0.01237991]
  [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432
   -0.02571746 -0.04351426  0.04922808  0.03779388  0.01237991]
  [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432
   -0.02571746 -0.04351426  0.04922808  0.03779388  0.01237991]
  [ 0.01703241  0.00141624  0.01836063 -0.04050465 -0.00021738
    0.0470962  -0.04713834 -0.0145869  -0.0093541   0.00981445]
  [-0.04526804 -0.00512029  0.00670778  0.00324589 -0.03528035
    0.02890212 -0.03655505 -0.04958206 -0.02427058 -0.02469977]
  [-0.00189484 -0.03842533 -0.04435733 -0.04152895  0.03780557
    0.00536566  0.03029987 -0.04246242 -0.0376426   0.04025837]
  [ 0.00549199 -0.00212338 -0.00701446 -0.01503222 -0.0376

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6348, 3985, 2764, 4983])

In [20]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 42ms/step
[[-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432 -0.02571746
  -0.04351426  0.04922808  0.03779388  0.01237991]
 [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432 -0.02571746
  -0.04351426  0.04922808  0.03779388  0.01237991]
 [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432 -0.02571746
  -0.04351426  0.04922808  0.03779388  0.01237991]
 [-0.00713933  0.02670025  0.00955595 -0.01016245 -0.02612432 -0.02571746
  -0.04351426  0.04922808  0.03779388  0.01237991]
 [ 0.01703241  0.00141624  0.01836063 -0.04050465 -0.00021738  0.0470962
  -0.04713834 -0.0145869  -0.0093541   0.00981445]
 [-0.04526804 -0.00512029  0.00670778  0.00324589 -0.03528035  0.02890212
  -0.03655505 -0.04958206 -0.02427058 -0.02469977]
 [-0.00189484 -0.03842533 -0.04435733 -0.04152895  0.03780557  0.00536566
   0.03029987 -0.04246242 -0.0376426   0.04025837]
 [ 0.00549199 -0.00212338 -0.00701446 -0.01503222 -0.03766634  0.02598417


### Assignment

In [21]:
sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [22]:
sent1

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### Vocabulary size
voc_size=10000

# One Hot Representation

In [33]:
onehot_repr=[one_hot(words,voc_size)for words in sent1] 
print(onehot_repr)

[[6348, 9475, 7667, 8337, 2825, 4489], [75, 2460, 7667, 3637, 2561, 1452], [5913, 7132, 4810, 9056], [6348, 157, 7667, 9457, 6348, 9875], [2088, 7557, 7949, 7667, 3637, 2561, 1452], [5826, 7667, 3637, 2561, 115, 3335]]


# Word Embedding Represntation

In [34]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
import numpy as np

In [36]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6348 9475 7667 8337 2825 4489]
 [   0    0    0    0   75 2460 7667 3637 2561 1452]
 [   0    0    0    0    0    0 5913 7132 4810 9056]
 [   0    0    0    0 6348  157 7667 9457 6348 9875]
 [   0    0    0 2088 7557 7949 7667 3637 2561 1452]
 [   0    0    0    0 5826 7667 3637 2561  115 3335]]


In [37]:
## 10 feature dimesnions
dim=12

In [38]:
model=Sequential()
model.add(Embedding(voc_size,12,input_length=sent_length))
model.compile('adam','mse')

In [39]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 10, 12)            120000    
                                                                 
Total params: 120,000
Trainable params: 120,000
Non-trainable params: 0
_________________________________________________________________


In [40]:
embedded_docs[0]

array([   0,    0,    0,    0, 6348, 9475, 7667, 8337, 2825, 4489])

In [41]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 93ms/step


array([[-0.0036063 , -0.03117271,  0.00059156, -0.03663672, -0.01399361,
         0.03782359,  0.0457312 ,  0.00506556,  0.00777682, -0.02364774,
         0.03204506, -0.03281868],
       [-0.0036063 , -0.03117271,  0.00059156, -0.03663672, -0.01399361,
         0.03782359,  0.0457312 ,  0.00506556,  0.00777682, -0.02364774,
         0.03204506, -0.03281868],
       [-0.0036063 , -0.03117271,  0.00059156, -0.03663672, -0.01399361,
         0.03782359,  0.0457312 ,  0.00506556,  0.00777682, -0.02364774,
         0.03204506, -0.03281868],
       [-0.0036063 , -0.03117271,  0.00059156, -0.03663672, -0.01399361,
         0.03782359,  0.0457312 ,  0.00506556,  0.00777682, -0.02364774,
         0.03204506, -0.03281868],
       [-0.02968756,  0.01241865,  0.04049962,  0.01787037,  0.01975818,
         0.04434757, -0.02851035, -0.01726363,  0.00042265,  0.01195525,
        -0.03567106, -0.02498188],
       [ 0.02856943,  0.03816006, -0.01494343, -0.00318003,  0.00392413,
        -0.00932121, -

In [42]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 96ms/step
[[[-3.60629708e-03 -3.11727058e-02  5.91564924e-04 -3.66367213e-02
   -1.39936097e-02  3.78235914e-02  4.57311980e-02  5.06556034e-03
    7.77681917e-03 -2.36477386e-02  3.20450552e-02 -3.28186750e-02]
  [-3.60629708e-03 -3.11727058e-02  5.91564924e-04 -3.66367213e-02
   -1.39936097e-02  3.78235914e-02  4.57311980e-02  5.06556034e-03
    7.77681917e-03 -2.36477386e-02  3.20450552e-02 -3.28186750e-02]
  [-3.60629708e-03 -3.11727058e-02  5.91564924e-04 -3.66367213e-02
   -1.39936097e-02  3.78235914e-02  4.57311980e-02  5.06556034e-03
    7.77681917e-03 -2.36477386e-02  3.20450552e-02 -3.28186750e-02]
  [-3.60629708e-03 -3.11727058e-02  5.91564924e-04 -3.66367213e-02
   -1.39936097e-02  3.78235914e-02  4.57311980e-02  5.06556034e-03
    7.77681917e-03 -2.36477386e-02  3.20450552e-02 -3.28186750e-02]
  [-2.96875592e-02  1.24186501e-02  4.04996164e-02  1.78703703e-02
    1.97581761e-02  4.43475731e-02 -2.85103451e-02 -1.72636285e-02
    4.